FROM python:3.10
WORKDIR /
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python
COPY . .
EXPOSE 5000
CMD [ "python", "server.py" ]